SRC= src/
INC= include/
INCL= -I$(INC)
ifdef OS # Windows' case
	ISDL= -IC:\\msys64\\mingw64\\include\\SDL
	EXT= dll
	RM= del
else
	ISDL= -I/c/msys64/mingw64/include/SDL
	EXT= so
	RM= rm
endif
LSDL=-lmingw32 -lSDLmain -lSDL -lSDL_image -lSDL_ttf -lSDL_gfx -lSDL_mixer

exe : main.o
	gcc -o Sonic main.o maputils.o sprites.o $(INCL) $(LSDL)

main.o : $(SRC)main.c maputils.o
	gcc -c $(SRC)main.c $(INCL) $(ISDL)

maputils.o : $(SRC)maputils.c $(INC)maputils.h sprites.o
	gcc -c $(SRC)maputils.c $(INCL) $(ISDL)

sprites.o : $(SRC)sprites.c $(INC)sprites.h
	gcc -c $(SRC)sprites.c $(INCL) $(ISDL)

clean :
	$(RM) *.o

