SRC= src/
INC= include/
INCL= -I$(INC)
ifdef OS # Windows' case
	ISDL= -IC:\\msys64\\mingw64\\include\\SDL
	RM= del
else
	ISDL= -I/c/msys64/mingw64/include/SDL
	RM= rm
endif
LSDL= -lmingw32 -lSDLmain -lSDL -lSDL_image -lSDL_ttf -lSDL_gfx -lSDL_mixer
INCLUDES= $(INCL) $(ISDL)

all : main.o
	gcc -o Sonic main.o green_hill.o maputils.o sprites.o $(INCL) $(LSDL)

main.o : $(SRC)main.c green_hill.o
	gcc -c $(SRC)main.c $(INCLUDES)

green_hill.o : $(SRC)green_hill.c maputils.o
	gcc -c $(SRC)green_hill.c $(INCLUDES)

maputils.o : $(SRC)maputils.c $(INC)maputils.h sprites.o
	gcc -c $(SRC)maputils.c $(INCLUDES)

sprites.o : $(SRC)sprites.c $(INC)sprites.h
	gcc -c $(SRC)sprites.c $(INCLUDES)

clean :
	$(RM) *.o